### Numpy - Numerical Python

- Used for working with array
- Used for Numerical Cal and Complex Cal

In [ ]:
### Why Numply is faster than Py data structure??

- Numpy is built upon C and C Language is hardware friendly language.
- An array is collection of homogeous data types that are stored in continous memory location. But Python data structure is collection of hectrogenous data types and it stored in non-continoues memory location.

### Numpy Used in 

- Linear Algebra
- Statistics
- Image Processing
- Matrix


- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [3]:
n1 = np.array([66,49,46,16,98,46,64,94])

In [4]:
n1

array([66, 49, 46, 16, 98, 46, 64, 94])

In [5]:
type(n1)

numpy.ndarray

In [6]:
n1 = np.array([66,49,46,16,98,46,64,94],dtype='int64')

In [7]:
n1

array([66, 49, 46, 16, 98, 46, 64, 94], dtype=int64)

In [8]:
n1 = np.array([66,49,46,16,98,46,64,94],dtype='complex')

In [9]:
n1

array([66.+0.j, 49.+0.j, 46.+0.j, 16.+0.j, 98.+0.j, 46.+0.j, 64.+0.j,
       94.+0.j])

In [10]:
n1/2

array([33. +0.j, 24.5+0.j, 23. +0.j,  8. +0.j, 49. +0.j, 23. +0.j,
       32. +0.j, 47. +0.j])

In [11]:
n1 = np.array([66,49,46,16,98,46,64,94],dtype='int64')

In [12]:
n1

array([66, 49, 46, 16, 98, 46, 64, 94], dtype=int64)

In [13]:
n1*2

array([132,  98,  92,  32, 196,  92, 128, 188], dtype=int64)

In [14]:
n1.mean()

59.875

In [15]:
n1.itemsize*len(n1)

64

In [16]:
l1 = [66,49,46,16,98,46,64,94]

In [17]:
import sys

In [18]:
sys.getsizeof(98)*len(l1)

224

- Numpy takes less memory than List and Tuple.

In [19]:
n1.ndim    #1D

1

In [20]:
n2 = np.array([[10,15,17],[52,41,85]])

In [21]:
n2

array([[10, 15, 17],
       [52, 41, 85]])

In [22]:
n2.ndim

2

In [23]:
n3 = np.array([['Name','Prashant'],['Gender','Male'],['Sal',48750]])

In [24]:
n3

array([['Name', 'Prashant'],
       ['Gender', 'Male'],
       ['Sal', '48750']], dtype='<U11')

In [25]:
n3.shape #(r,c)

(3, 2)

In [26]:
n3[0][1]

'Prashant'

In [27]:
n4 = np.array([[[56,65,40,65],[66,35,56,65]],[[64,66,46,46],[64,94,93,44]]])

In [28]:
n4.ndim

3

In [29]:
n4

array([[[56, 65, 40, 65],
        [66, 35, 56, 65]],

       [[64, 66, 46, 46],
        [64, 94, 93, 44]]])

In [30]:
n4[1][0][3]

46

In [31]:
n4[1][1][3]

44

In [32]:
n4[0][0][3]

65

In [33]:
n4[1][0][1]

66

In [34]:
n0 = np.array([[['Suyash','Neel','Nikhil'],['Mayank','Varun','Harish']],
               [[45,50,80,],[45,50,60]]])

In [35]:
n0

array([[['Suyash', 'Neel', 'Nikhil'],
        ['Mayank', 'Varun', 'Harish']],

       [['45', '50', '80'],
        ['45', '50', '60']]], dtype='<U11')

In [36]:
n0.ndim

3

In [37]:
n0[0][0][2]

'Nikhil'

In [38]:
n0.shape   #(z,r,c)

(2, 2, 3)

In [39]:
n2

array([[10, 15, 17],
       [52, 41, 85]])

In [40]:
n2.reshape(3,2)

array([[10, 15],
       [17, 52],
       [41, 85]])

In [41]:
n3.reshape(2,3)

array([['Name', 'Prashant', 'Gender'],
       ['Male', 'Sal', '48750']], dtype='<U11')

In [42]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.zeros([10,12])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.ones([10,12])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
np.ones([2,2,6])

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [47]:
np.zeros([2,4,10])

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

#### Difference Between Dot and Multiplication

- Multiplication of two real numbers gives you back a real number, whereas the dot product of two vectors in general does not give you back a vector of the same space, but a real number 

In [48]:
n11 = np.array([[66,34],[61,38]])

In [49]:
n11

array([[66, 34],
       [61, 38]])

In [50]:
n12 = np.array([[46,84],[50,70]])

In [51]:
n12

array([[46, 84],
       [50, 70]])

In [52]:
np.multiply(n11,n12)

array([[3036, 2856],
       [3050, 2660]])

In [53]:
np.dot(n11,n12)

array([[4736, 7924],
       [4706, 7784]])

In [54]:
#Generate Seq Of No.
np.arange(10,25,2)

array([10, 12, 14, 16, 18, 20, 22, 24])

In [55]:
#indentity Matrix
np.eye(2,7,dtype='int')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0]])

In [56]:
np.eye(4,4,dtype='complex')

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [57]:
np.identity(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [58]:
#to generate random no.
np.random.randint(245)

144

In [59]:
#0-1
np.random.rand(25) 

array([0.98586038, 0.13967727, 0.26404407, 0.20176145, 0.32088687,
       0.15525493, 0.20963152, 0.67039913, 0.55135496, 0.27477091,
       0.40945014, 0.43974492, 0.59831009, 0.87674103, 0.72659356,
       0.31420738, 0.36987579, 0.9267731 , 0.02399868, 0.22890383,
       0.48353378, 0.10067984, 0.23086347, 0.82529818, 0.22001307])

In [60]:
np.random.randint(15,35,size=[5,4])

array([[32, 17, 31, 22],
       [15, 23, 25, 18],
       [23, 21, 15, 15],
       [29, 24, 15, 25],
       [21, 26, 20, 26]])

In [61]:
np.random.randint(15,50,size=[3,5])

array([[17, 15, 39, 46, 47],
       [44, 31, 30, 46, 39],
       [28, 27, 39, 17, 16]])

In [62]:
np.full((2,2),45)

array([[45, 45],
       [45, 45]])

### Statistics

#### Types Of Statstics

- Descriptive statistics
- Inferential statistics

#### 1.Descriptive statistics

- In this type of statistics, the data is summarised through the given observations. The summarisation is one from a sample of population using parameters such as the mean or standard deviation.
- Descriptive statistics is a way to organise, represent and describe a collection of data using tables, graphs, and summary measures. For example, the collection of people in a city using the internet or using Television.

#### 2.Inferential statistics

- This type of statistics is used to interpret the meaning of Descriptive statistics. That means once the data has been collected, analysed and summarised then we use these stats to describe the meaning of the collected data. Or we can say, it is used to draw conclusions from the data that depends on random variations such as observational errors, sampling variation, etc.
- Inferential Statistics is a method that allows us to use information collected from a sample to make decisions, predictions or inferences from a population. It grants us permission to give statements that goes beyond the available data or information.

- Mean
- Median
- Mode
- Standard Deviation
- Variance

In [63]:
S1 = [168,170,150,160,182,140,175,191,152,150]

In [64]:
S1

[168, 170, 150, 160, 182, 140, 175, 191, 152, 150]

#### 1.Mean

- Mean is Sum of all data No. divided by No.of Values

In [65]:
np.mean(S1)

163.8

#### 2.Median

- Median is Mid Value in Ordered data set.
- Step 1: Arrange data in increasing order 
- Step 2: Determine how many numbers are in the data set = n 
- Step 3:  If n is odd: Median is the middle number and if n is even: Median is the average of two middle numbers 

In [66]:
np.median(S1)

164.0

#### 3.Mode

- Mode is No. which occures most often in data set.

In [67]:
from scipy import stats

In [68]:
stats.mode(S1)

C:\Users\tsd95\AppData\Local\Temp\ipykernel_8056\1378483382.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(S1)


ModeResult(mode=array([150]), count=array([2]))

#### 4.Variance

- Variance is the numerical values that describe the variability of the observations from its arithmetic mean 

In [69]:
np.var(S1)

235.35999999999999

#### 5.Standard Deviation

- It is a measure of dispersion of observation within dataset relative to their mean.
- std div is Square root of variance

In [70]:
np.std(S1)

15.341447128612085

#### Floor and Ceil

In [71]:
c1 = np.array([54.2,65.8,16.7,59.3,75.6])

In [72]:
np.floor(c1)

array([54., 65., 16., 59., 75.])

In [73]:
np.ceil(c1)

array([55., 66., 17., 60., 76.])

In [74]:
c2 = np.array([-2.1,-3.8,-7.9,-9.2,-6.6])

In [75]:
c2

array([-2.1, -3.8, -7.9, -9.2, -6.6])

In [76]:
np.floor(c2)

array([ -3.,  -4.,  -8., -10.,  -7.])

In [77]:
np.ceil(c2)

array([-2., -3., -7., -9., -6.])

### End Here

##### Start Part 2

In [78]:
a = np.array([1,2,3])

In [79]:
type(a)

numpy.ndarray

In [80]:
a.ndim

1

In [81]:
a[2]

3

In [82]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [83]:
b.ndim

2

In [84]:
b.dtype

dtype('int32')

In [85]:
c=np.array([[4,5,6],[7,8,9]])

In [86]:
c.ndim

2

In [87]:
b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
b[1,2]

6

In [89]:
b[1,2]=20

In [90]:
b

array([[ 1,  2,  3],
       [ 4,  5, 20],
       [ 7,  8,  9]])

In [91]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [92]:
np.ones((45,45))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [93]:
np.full((2,2),45)

array([[45, 45],
       [45, 45]])

In [94]:
np.random.randint(3,45,size=(3,3))

array([[39,  4, 43],
       [18, 43, 15],
       [42, 38, 16]])

In [95]:
np.identity(4,dtype='int32')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [96]:
x = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [97]:
y= np.array(([1,2,3],[4,5,6],[7,8,9]))

In [98]:
x*y

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [99]:
x/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [100]:
x+y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [101]:
np.max(a)

3

In [102]:
np.mean(a)

2.0

In [103]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [104]:
x.shape

(3, 3)

In [105]:
z= np.array(([1,2,3],[4,5,6]))

In [106]:
t=np.array(([1,2,3],[4,5,6]))

In [107]:
z*t

array([[ 1,  4,  9],
       [16, 25, 36]])

In [108]:
z.shape

(2, 3)

In [109]:
z.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [110]:
g=np.genfromtxt(r"C:\Users\tsd95\CSV Files\Model\test.csv",delimiter=',')

In [111]:
g

array([[ nan,  nan,  nan],
       [105.,  nan,  nan],
       [106.,  nan,  nan],
       [107.,  nan,  nan]])