### Machine Learning

- ML is type of Artificial Intelligence(AI) that allow software applications to become more accurate at predicting Outcomes.
- ML algorithm use historical data as input to predict output values.

### Exploratory Data Analysis

- EDA is most important step in data analysis or in Data Science project.
- EDA is process of invesgating dataset to discover pattern,outliers and form hypothesis based on our understanding of the dataset.

###### Types Of ML

- Supervised.
- Unsupervised.
- Reinforcement.

###### DataFrame

- A DF is data structure that oraganizes data into 2-D tables of rows and Cols.

### Pandas

- Pandas is python package providing fast,flexible and expressive data structure designed to make working with "relational" or "labeled" data.

###### Types of data structure

- Series (1D)
- DataFrame (2D)
- Panel (More than 2D)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\tsd95\CSV Files\customer_shopping_data.csv")

In [3]:
df

invoice_no customer_id  gender  age         category  quantity    price  \
0        I138884     C241288  Female   28         Clothing         5  1500.40   
1        I317333     C111565    Male   21            Shoes         3  1800.51   
2        I127801     C266599    Male   20         Clothing         1   300.08   
3        I173702     C988172  Female   66            Shoes         5  3000.85   
4        I337046     C189076  Female   53            Books         4    60.60   
...          ...         ...     ...  ...              ...       ...      ...   
99452    I219422     C441542  Female   45         Souvenir         5    58.65   
99453    I325143     C569580    Male   27  Food & Beverage         2    10.46   
99454    I824010     C103292    Male   63  Food & Beverage         2    10.46   
99455    I702964     C800631    Male   56       Technology         4  4200.00   
99456    I232867     C273973  Female   36         Souvenir         3    35.19   

      payment_method invoice_date     shopping_mall  
0        Credit Card   05-08-2022            Kanyon  
1         Debit Card   12-12-2021    Forum Istanbul  
2               Cash   09-11-2021         Metrocity  
3        Credit Card   16-05-2021      Metropol AVM  
4               Cash   24-10-2021            Kanyon  
...              ...          ...               ...  
99452    Credit Card   21-09-2022            Kanyon  
99453           Cash   22-09-2021    Forum Istanbul  
99454     Debit Card   28-03-2021         Metrocity  
99455           Cash   16-03-2021      Istinye Park  
99456    Credit Card   15-10-2022  Mall of Istanbul  

[99457 rows x 10 columns]

In [4]:
df.shape

(99457, 10)

In [5]:
df.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall'],
      dtype='object')

In [6]:
df.describe().T

count        mean         std    min    25%    50%      75%  \
age       99457.0   43.427089   14.990054  18.00  30.00   43.0    56.00   
quantity  99457.0    3.003429    1.413025   1.00   2.00    3.0     4.00   
price     99457.0  689.256321  941.184567   5.23  45.45  203.3  1200.32   

             max  
age         69.0  
quantity     5.0  
price     5250.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   invoice_no      99457 non-null  object 
 1   customer_id     99457 non-null  object 
 2   gender          99457 non-null  object 
 3   age             99457 non-null  int64  
 4   category        99457 non-null  object 
 5   quantity        99457 non-null  int64  
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object 
 8   invoice_date    99457 non-null  object 
 9   shopping_mall   99457 non-null  object 
dtypes: float64(1), int64(2), object(7)
memory usage: 7.6+ MB


In [8]:
df.dtypes

invoice_no         object
customer_id        object
gender             object
age                 int64
category           object
quantity            int64
price             float64
payment_method     object
invoice_date       object
shopping_mall      object
dtype: object

In [9]:
df.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [10]:
df.head()

invoice_no customer_id  gender  age  category  quantity    price  \
0    I138884     C241288  Female   28  Clothing         5  1500.40   
1    I317333     C111565    Male   21     Shoes         3  1800.51   
2    I127801     C266599    Male   20  Clothing         1   300.08   
3    I173702     C988172  Female   66     Shoes         5  3000.85   
4    I337046     C189076  Female   53     Books         4    60.60   

  payment_method invoice_date   shopping_mall  
0    Credit Card   05-08-2022          Kanyon  
1     Debit Card   12-12-2021  Forum Istanbul  
2           Cash   09-11-2021       Metrocity  
3    Credit Card   16-05-2021    Metropol AVM  
4           Cash   24-10-2021          Kanyon

In [11]:
df.tail()

invoice_no customer_id  gender  age         category  quantity    price  \
99452    I219422     C441542  Female   45         Souvenir         5    58.65   
99453    I325143     C569580    Male   27  Food & Beverage         2    10.46   
99454    I824010     C103292    Male   63  Food & Beverage         2    10.46   
99455    I702964     C800631    Male   56       Technology         4  4200.00   
99456    I232867     C273973  Female   36         Souvenir         3    35.19   

      payment_method invoice_date     shopping_mall  
99452    Credit Card   21-09-2022            Kanyon  
99453           Cash   22-09-2021    Forum Istanbul  
99454     Debit Card   28-03-2021         Metrocity  
99455           Cash   16-03-2021      Istinye Park  
99456    Credit Card   15-10-2022  Mall of Istanbul

In [12]:
df.sample()

invoice_no customer_id gender  age         category  quantity  price  \
68181    I121416     C176937   Male   55  Food & Beverage         1   5.23   

      payment_method invoice_date shopping_mall  
68181    Credit Card   18-09-2022        Kanyon

In [13]:
df.sample(10)

invoice_no customer_id  gender  age         category  quantity    price  \
14442    I544852     C307609  Female   30            Shoes         1   600.17   
91998    I108232     C795933  Female   24            Books         3    45.45   
1123     I120560     C291970    Male   37         Clothing         3   900.24   
60318    I143185     C333970  Female   50        Cosmetics         1    40.66   
29709    I260347     C323204  Female   56       Technology         5  5250.00   
81350    I900046     C151127  Female   50         Souvenir         2    23.46   
9257     I276631     C109551    Male   44             Toys         4   143.36   
81641    I298769     C337438  Female   21             Toys         1    35.84   
32176    I387385     C434376  Female   23         Clothing         1   300.08   
97832    I945263     C174906  Female   37  Food & Beverage         3    15.69   

      payment_method invoice_date      shopping_mall  
14442    Credit Card   12-06-2021             Kanyon  
91998    Credit Card   24-09-2022   Mall of Istanbul  
1123            Cash   28-12-2022       Metropol AVM  
60318    Credit Card   15-04-2021       Zorlu Center  
29709           Cash   13-06-2022             Kanyon  
81350           Cash   31-05-2022             Kanyon  
9257      Debit Card   25-12-2021       Istinye Park  
81641    Credit Card   15-12-2021       Zorlu Center  
32176           Cash   06-04-2022  Emaar Square Mall  
97832           Cash   11-08-2021     Forum Istanbul

In [14]:
df.head(8)

invoice_no customer_id  gender  age   category  quantity    price  \
0    I138884     C241288  Female   28   Clothing         5  1500.40   
1    I317333     C111565    Male   21      Shoes         3  1800.51   
2    I127801     C266599    Male   20   Clothing         1   300.08   
3    I173702     C988172  Female   66      Shoes         5  3000.85   
4    I337046     C189076  Female   53      Books         4    60.60   
5    I227836     C657758  Female   28   Clothing         5  1500.40   
6    I121056     C151197  Female   49  Cosmetics         1    40.66   
7    I293112     C176086  Female   32   Clothing         2   600.16   

  payment_method invoice_date     shopping_mall  
0    Credit Card   05-08-2022            Kanyon  
1     Debit Card   12-12-2021    Forum Istanbul  
2           Cash   09-11-2021         Metrocity  
3    Credit Card   16-05-2021      Metropol AVM  
4           Cash   24-10-2021            Kanyon  
5    Credit Card   24-05-2022    Forum Istanbul  
6           Cash   13-03-2022      Istinye Park  
7    Credit Card   13-01-2021  Mall of Istanbul

In [15]:
df['category'].value_counts()

Clothing           34487
Cosmetics          15097
Food & Beverage    14776
Toys               10087
Shoes              10034
Souvenir            4999
Technology          4996
Books               4981
Name: category, dtype: int64

In [16]:
df['category'].unique()

array(['Clothing', 'Shoes', 'Books', 'Cosmetics', 'Food & Beverage',
       'Toys', 'Technology', 'Souvenir'], dtype=object)

In [17]:
df['Invoice Year'] = df['invoice_date'].apply((lambda x:x.split('-')[2]))

In [18]:
df

invoice_no customer_id  gender  age         category  quantity    price  \
0        I138884     C241288  Female   28         Clothing         5  1500.40   
1        I317333     C111565    Male   21            Shoes         3  1800.51   
2        I127801     C266599    Male   20         Clothing         1   300.08   
3        I173702     C988172  Female   66            Shoes         5  3000.85   
4        I337046     C189076  Female   53            Books         4    60.60   
...          ...         ...     ...  ...              ...       ...      ...   
99452    I219422     C441542  Female   45         Souvenir         5    58.65   
99453    I325143     C569580    Male   27  Food & Beverage         2    10.46   
99454    I824010     C103292    Male   63  Food & Beverage         2    10.46   
99455    I702964     C800631    Male   56       Technology         4  4200.00   
99456    I232867     C273973  Female   36         Souvenir         3    35.19   

      payment_method invoice_date     shopping_mall Invoice Year  
0        Credit Card   05-08-2022            Kanyon         2022  
1         Debit Card   12-12-2021    Forum Istanbul         2021  
2               Cash   09-11-2021         Metrocity         2021  
3        Credit Card   16-05-2021      Metropol AVM         2021  
4               Cash   24-10-2021            Kanyon         2021  
...              ...          ...               ...          ...  
99452    Credit Card   21-09-2022            Kanyon         2022  
99453           Cash   22-09-2021    Forum Istanbul         2021  
99454     Debit Card   28-03-2021         Metrocity         2021  
99455           Cash   16-03-2021      Istinye Park         2021  
99456    Credit Card   15-10-2022  Mall of Istanbul         2022  

[99457 rows x 11 columns]

In [19]:
#to rename
df.columns=['Invoice_no', 'Customer_id', 'Gender', 'Age', 'Category', 'Quantity',
       'Price', 'Payment_method', 'Invoice_date', 'Shopping_mall','Invoice Year']

In [20]:
df['Payment_method'].value_counts()

Cash           44447
Credit Card    34931
Debit Card     20079
Name: Payment_method, dtype: int64

In [21]:
#single col delete

df.drop('Invoice Year',axis=1,inplace=True)

In [22]:
df

Invoice_no Customer_id  Gender  Age         Category  Quantity    Price  \
0        I138884     C241288  Female   28         Clothing         5  1500.40   
1        I317333     C111565    Male   21            Shoes         3  1800.51   
2        I127801     C266599    Male   20         Clothing         1   300.08   
3        I173702     C988172  Female   66            Shoes         5  3000.85   
4        I337046     C189076  Female   53            Books         4    60.60   
...          ...         ...     ...  ...              ...       ...      ...   
99452    I219422     C441542  Female   45         Souvenir         5    58.65   
99453    I325143     C569580    Male   27  Food & Beverage         2    10.46   
99454    I824010     C103292    Male   63  Food & Beverage         2    10.46   
99455    I702964     C800631    Male   56       Technology         4  4200.00   
99456    I232867     C273973  Female   36         Souvenir         3    35.19   

      Payment_method Invoice_date     Shopping_mall  
0        Credit Card   05-08-2022            Kanyon  
1         Debit Card   12-12-2021    Forum Istanbul  
2               Cash   09-11-2021         Metrocity  
3        Credit Card   16-05-2021      Metropol AVM  
4               Cash   24-10-2021            Kanyon  
...              ...          ...               ...  
99452    Credit Card   21-09-2022            Kanyon  
99453           Cash   22-09-2021    Forum Istanbul  
99454     Debit Card   28-03-2021         Metrocity  
99455           Cash   16-03-2021      Istinye Park  
99456    Credit Card   15-10-2022  Mall of Istanbul  

[99457 rows x 10 columns]

In [23]:
#to delete multiple col

df.drop(columns=['Invoice_no','Invoice_date'],axis=1,inplace=True)

In [24]:
df

Customer_id  Gender  Age         Category  Quantity    Price  \
0         C241288  Female   28         Clothing         5  1500.40   
1         C111565    Male   21            Shoes         3  1800.51   
2         C266599    Male   20         Clothing         1   300.08   
3         C988172  Female   66            Shoes         5  3000.85   
4         C189076  Female   53            Books         4    60.60   
...           ...     ...  ...              ...       ...      ...   
99452     C441542  Female   45         Souvenir         5    58.65   
99453     C569580    Male   27  Food & Beverage         2    10.46   
99454     C103292    Male   63  Food & Beverage         2    10.46   
99455     C800631    Male   56       Technology         4  4200.00   
99456     C273973  Female   36         Souvenir         3    35.19   

      Payment_method     Shopping_mall  
0        Credit Card            Kanyon  
1         Debit Card    Forum Istanbul  
2               Cash         Metrocity  
3        Credit Card      Metropol AVM  
4               Cash            Kanyon  
...              ...               ...  
99452    Credit Card            Kanyon  
99453           Cash    Forum Istanbul  
99454     Debit Card         Metrocity  
99455           Cash      Istinye Park  
99456    Credit Card  Mall of Istanbul  

[99457 rows x 8 columns]

### iloc and loc

#### loc

- It is label based data selecting method which means we have to pass the name of col which we want to select.
- This method included that last element of the range passed in it.
- Range excluded.

In [25]:
df.loc[:,'Gender':'Quantity']

Gender  Age         Category  Quantity
0      Female   28         Clothing         5
1        Male   21            Shoes         3
2        Male   20         Clothing         1
3      Female   66            Shoes         5
4      Female   53            Books         4
...       ...  ...              ...       ...
99452  Female   45         Souvenir         5
99453    Male   27  Food & Beverage         2
99454    Male   63  Food & Beverage         2
99455    Male   56       Technology         4
99456  Female   36         Souvenir         3

[99457 rows x 4 columns]

In [26]:
df.loc[:,'Customer_id':'Price']

Customer_id  Gender  Age         Category  Quantity    Price
0         C241288  Female   28         Clothing         5  1500.40
1         C111565    Male   21            Shoes         3  1800.51
2         C266599    Male   20         Clothing         1   300.08
3         C988172  Female   66            Shoes         5  3000.85
4         C189076  Female   53            Books         4    60.60
...           ...     ...  ...              ...       ...      ...
99452     C441542  Female   45         Souvenir         5    58.65
99453     C569580    Male   27  Food & Beverage         2    10.46
99454     C103292    Male   63  Food & Beverage         2    10.46
99455     C800631    Male   56       Technology         4  4200.00
99456     C273973  Female   36         Souvenir         3    35.19

[99457 rows x 6 columns]

In [27]:
df.loc[:,'Age':'Quantity']

Age         Category  Quantity
0       28         Clothing         5
1       21            Shoes         3
2       20         Clothing         1
3       66            Shoes         5
4       53            Books         4
...    ...              ...       ...
99452   45         Souvenir         5
99453   27  Food & Beverage         2
99454   63  Food & Beverage         2
99455   56       Technology         4
99456   36         Souvenir         3

[99457 rows x 3 columns]

#### iloc()

- It is index based data selecting method which means we have to pass integer index of spacified col.
- Range included.

In [28]:
df.iloc[:,1:5]

Gender  Age         Category  Quantity
0      Female   28         Clothing         5
1        Male   21            Shoes         3
2        Male   20         Clothing         1
3      Female   66            Shoes         5
4      Female   53            Books         4
...       ...  ...              ...       ...
99452  Female   45         Souvenir         5
99453    Male   27  Food & Beverage         2
99454    Male   63  Food & Beverage         2
99455    Male   56       Technology         4
99456  Female   36         Souvenir         3

[99457 rows x 4 columns]

In [29]:
df.iloc[:,0:6]

Customer_id  Gender  Age         Category  Quantity    Price
0         C241288  Female   28         Clothing         5  1500.40
1         C111565    Male   21            Shoes         3  1800.51
2         C266599    Male   20         Clothing         1   300.08
3         C988172  Female   66            Shoes         5  3000.85
4         C189076  Female   53            Books         4    60.60
...           ...     ...  ...              ...       ...      ...
99452     C441542  Female   45         Souvenir         5    58.65
99453     C569580    Male   27  Food & Beverage         2    10.46
99454     C103292    Male   63  Food & Beverage         2    10.46
99455     C800631    Male   56       Technology         4  4200.00
99456     C273973  Female   36         Souvenir         3    35.19

[99457 rows x 6 columns]

In [30]:
df.iloc[:,1:5]

Gender  Age         Category  Quantity
0      Female   28         Clothing         5
1        Male   21            Shoes         3
2        Male   20         Clothing         1
3      Female   66            Shoes         5
4      Female   53            Books         4
...       ...  ...              ...       ...
99452  Female   45         Souvenir         5
99453    Male   27  Food & Beverage         2
99454    Male   63  Food & Beverage         2
99455    Male   56       Technology         4
99456  Female   36         Souvenir         3

[99457 rows x 4 columns]

### Group By

- Pandas dataframe.groupby() function is used to split the data into groups based on some criteria.
- pandas objects can be split on any of their axes.

In [31]:
df

Customer_id  Gender  Age         Category  Quantity    Price  \
0         C241288  Female   28         Clothing         5  1500.40   
1         C111565    Male   21            Shoes         3  1800.51   
2         C266599    Male   20         Clothing         1   300.08   
3         C988172  Female   66            Shoes         5  3000.85   
4         C189076  Female   53            Books         4    60.60   
...           ...     ...  ...              ...       ...      ...   
99452     C441542  Female   45         Souvenir         5    58.65   
99453     C569580    Male   27  Food & Beverage         2    10.46   
99454     C103292    Male   63  Food & Beverage         2    10.46   
99455     C800631    Male   56       Technology         4  4200.00   
99456     C273973  Female   36         Souvenir         3    35.19   

      Payment_method     Shopping_mall  
0        Credit Card            Kanyon  
1         Debit Card    Forum Istanbul  
2               Cash         Metrocity  
3        Credit Card      Metropol AVM  
4               Cash            Kanyon  
...              ...               ...  
99452    Credit Card            Kanyon  
99453           Cash    Forum Istanbul  
99454     Debit Card         Metrocity  
99455           Cash      Istinye Park  
99456    Credit Card  Mall of Istanbul  

[99457 rows x 8 columns]

In [32]:
df['Payment_method'].value_counts()

Cash           44447
Credit Card    34931
Debit Card     20079
Name: Payment_method, dtype: int64

In [33]:
Pay = df.groupby('Payment_method')

In [34]:
Pay.get_group('Cash')

Customer_id  Gender  Age         Category  Quantity    Price  \
2         C266599    Male   20         Clothing         1   300.08   
4         C189076  Female   53            Books         4    60.60   
6         C151197  Female   49        Cosmetics         1    40.66   
10        C240286  Female   36  Food & Beverage         2    10.46   
13        C312861    Male   25         Clothing         2   600.16   
...           ...     ...  ...              ...       ...      ...   
99449     C953724    Male   65         Clothing         1   300.08   
99450     C226974  Female   28            Books         1    15.15   
99451     C513603    Male   50             Toys         5   179.20   
99453     C569580    Male   27  Food & Beverage         2    10.46   
99455     C800631    Male   56       Technology         4  4200.00   

      Payment_method   Shopping_mall  
2               Cash       Metrocity  
4               Cash          Kanyon  
6               Cash    Istinye Park  
10              Cash       Metrocity  
13              Cash     Cevahir AVM  
...              ...             ...  
99449           Cash          Kanyon  
99450           Cash    Zorlu Center  
99451           Cash    Metropol AVM  
99453           Cash  Forum Istanbul  
99455           Cash    Istinye Park  

[44447 rows x 8 columns]

In [35]:
Pay.get_group('Credit Card')

Customer_id  Gender  Age  Category  Quantity    Price Payment_method  \
0         C241288  Female   28  Clothing         5  1500.40    Credit Card   
3         C988172  Female   66     Shoes         5  3000.85    Credit Card   
5         C657758  Female   28  Clothing         5  1500.40    Credit Card   
7         C176086  Female   32  Clothing         2   600.16    Credit Card   
8         C159642    Male   69  Clothing         3   900.24    Credit Card   
...           ...     ...  ...       ...       ...      ...            ...   
99433     C142643    Male   28      Toys         1    35.84    Credit Card   
99438     C363191  Female   47      Toys         5   179.20    Credit Card   
99448     C231387  Female   65     Shoes         4  2400.68    Credit Card   
99452     C441542  Female   45  Souvenir         5    58.65    Credit Card   
99456     C273973  Female   36  Souvenir         3    35.19    Credit Card   

          Shopping_mall  
0                Kanyon  
3          Metropol AVM  
5        Forum Istanbul  
7      Mall of Istanbul  
8             Metrocity  
...                 ...  
99433         Metrocity  
99438            Kanyon  
99448      Metropol AVM  
99452            Kanyon  
99456  Mall of Istanbul  

[34931 rows x 8 columns]

In [36]:
Pay.get_group('Debit Card')

Customer_id  Gender  Age         Category  Quantity    Price  \
1         C111565    Male   21            Shoes         3  1800.51   
12        C225330  Female   67             Toys         4   143.36   
16        C300786    Male   65            Books         2    30.30   
25        C285161    Male   51             Toys         2    71.68   
30        C159164  Female   66             Toys         3   107.52   
...           ...     ...  ...              ...       ...      ...   
99426     C145665  Female   19            Shoes         1   600.17   
99432     C289915  Female   41            Books         2    30.30   
99442     C131810  Female   45         Clothing         4  1200.32   
99443     C223470    Male   41        Cosmetics         4   162.64   
99454     C103292    Male   63  Food & Beverage         2    10.46   

      Payment_method     Shopping_mall  
1         Debit Card    Forum Istanbul  
12        Debit Card         Metrocity  
16        Debit Card         Metrocity  
25        Debit Card      Istinye Park  
30        Debit Card  Mall of Istanbul  
...              ...               ...  
99426     Debit Card      Istinye Park  
99432     Debit Card  Mall of Istanbul  
99442     Debit Card      Istinye Park  
99443     Debit Card  Mall of Istanbul  
99454     Debit Card         Metrocity  

[20079 rows x 8 columns]

In [37]:
gen = df.groupby('Gender')

In [38]:
gen.get_group('Female')

Customer_id  Gender  Age   Category  Quantity    Price Payment_method  \
0         C241288  Female   28   Clothing         5  1500.40    Credit Card   
3         C988172  Female   66      Shoes         5  3000.85    Credit Card   
4         C189076  Female   53      Books         4    60.60           Cash   
5         C657758  Female   28   Clothing         5  1500.40    Credit Card   
6         C151197  Female   49  Cosmetics         1    40.66           Cash   
...           ...     ...  ...        ...       ...      ...            ...   
99447     C288090  Female   37       Toys         3   107.52           Cash   
99448     C231387  Female   65      Shoes         4  2400.68    Credit Card   
99450     C226974  Female   28      Books         1    15.15           Cash   
99452     C441542  Female   45   Souvenir         5    58.65    Credit Card   
99456     C273973  Female   36   Souvenir         3    35.19    Credit Card   

          Shopping_mall  
0                Kanyon  
3          Metropol AVM  
4                Kanyon  
5        Forum Istanbul  
6          Istinye Park  
...                 ...  
99447      Metropol AVM  
99448      Metropol AVM  
99450      Zorlu Center  
99452            Kanyon  
99456  Mall of Istanbul  

[59482 rows x 8 columns]

In [39]:
gen.get_group('Male')

Customer_id Gender  Age         Category  Quantity    Price  \
1         C111565   Male   21            Shoes         3  1800.51   
2         C266599   Male   20         Clothing         1   300.08   
8         C159642   Male   69         Clothing         3   900.24   
13        C312861   Male   25         Clothing         2   600.16   
15        C362288   Male   24            Shoes         5  3000.85   
...           ...    ...  ...              ...       ...      ...   
99449     C953724   Male   65         Clothing         1   300.08   
99451     C513603   Male   50             Toys         5   179.20   
99453     C569580   Male   27  Food & Beverage         2    10.46   
99454     C103292   Male   63  Food & Beverage         2    10.46   
99455     C800631   Male   56       Technology         4  4200.00   

      Payment_method   Shopping_mall  
1         Debit Card  Forum Istanbul  
2               Cash       Metrocity  
8        Credit Card       Metrocity  
13              Cash     Cevahir AVM  
15       Credit Card  Viaport Outlet  
...              ...             ...  
99449           Cash          Kanyon  
99451           Cash    Metropol AVM  
99453           Cash  Forum Istanbul  
99454     Debit Card       Metrocity  
99455           Cash    Istinye Park  

[39975 rows x 8 columns]

In [40]:
df['Age'].max()

69

In [41]:
df['Age'].min()

18

In [42]:
df['Price'].mean()

689.2563209226097

In [43]:
df['Price'].median()

203.3

In [44]:
df.sort_values('Age')

Customer_id  Gender  Age  Category  Quantity    Price Payment_method  \
69089     C167489    Male   18     Shoes         3  1800.51     Debit Card   
95060     C687788    Male   18      Toys         4   143.36           Cash   
78728     C142284  Female   18  Clothing         2   600.16     Debit Card   
55784     C525437  Female   18     Books         2    30.30           Cash   
2443      C338582    Male   18     Shoes         5  3000.85     Debit Card   
...           ...     ...  ...       ...       ...      ...            ...   
66267     C202678    Male   69      Toys         5   179.20    Credit Card   
66279     C176169  Female   69     Shoes         2  1200.34    Credit Card   
85428     C208685  Female   69  Souvenir         2    23.46           Cash   
66133     C345511  Female   69  Clothing         1   300.08    Credit Card   
62421     C302779  Female   69  Clothing         5  1500.40           Cash   

          Shopping_mall  
69089            Kanyon  
95060  Mall of Istanbul  
78728    Forum Istanbul  
55784    Forum Istanbul  
2443       Istinye Park  
...                 ...  
66267      Istinye Park  
66279    Viaport Outlet  
85428         Metrocity  
66133  Mall of Istanbul  
62421      Metropol AVM  

[99457 rows x 8 columns]

In [45]:
df.set_index('Customer_id')

Gender  Age         Category  Quantity    Price Payment_method  \
Customer_id                                                                   
C241288      Female   28         Clothing         5  1500.40    Credit Card   
C111565        Male   21            Shoes         3  1800.51     Debit Card   
C266599        Male   20         Clothing         1   300.08           Cash   
C988172      Female   66            Shoes         5  3000.85    Credit Card   
C189076      Female   53            Books         4    60.60           Cash   
...             ...  ...              ...       ...      ...            ...   
C441542      Female   45         Souvenir         5    58.65    Credit Card   
C569580        Male   27  Food & Beverage         2    10.46           Cash   
C103292        Male   63  Food & Beverage         2    10.46     Debit Card   
C800631        Male   56       Technology         4  4200.00           Cash   
C273973      Female   36         Souvenir         3    35.19    Credit Card   

                Shopping_mall  
Customer_id                    
C241288                Kanyon  
C111565        Forum Istanbul  
C266599             Metrocity  
C988172          Metropol AVM  
C189076                Kanyon  
...                       ...  
C441542                Kanyon  
C569580        Forum Istanbul  
C103292             Metrocity  
C800631          Istinye Park  
C273973      Mall of Istanbul  

[99457 rows x 7 columns]

In [46]:
dfNull = pd.read_csv(r"C:\Users\tsd95\CSV Files\Model\NullValues.csv")

In [47]:
dfNull

ID        NAME   AGE      SAL               EMAIL       LOC
0   105.0        Anil  32.0      NaN      anil@gmail.com      Pune
1   106.0      Chetan   NaN  98000.0      chet@yahoo.com     Pawai
2   114.0      Jayesh  27.0  65000.0  jayesh@outlook.com     Thane
3     NaN      Harish  25.0      NaN    harish@gmail.com       NaN
4   120.0       Komal  28.0  59700.0     komal@yahoo.com   Sangali
5   135.0         NaN   NaN  78700.0                 NaN  Hydrabad
6   140.0      Sachin  29.0  45700.0    sachin@gmail.com  Kolhapur
7   135.0  Vijaykumar  32.0  46940.0     vijay@yahoo.com  Kolhapur
8   498.0       Kiran   NaN  61649.0     kamal@gmail.com     Panji
9     NaN         NaN  25.0  76464.0                 NaN    Barshi
10  416.0      Bharat   NaN  98746.0    bharat@gmail.com     Latur
11    NaN         NaN  40.0      NaN    sachin@gmail.com      Pune
12  489.0     Pratham  25.0  46479.0   pratham@gmail.com       NaN
13  162.0       Shlok  27.0  46497.0                 NaN       NaN
14  648.0         NaN  24.0  45404.0    kanika@gmail.com       NaN

In [48]:
dfNull.isnull().sum()

ID       3
NAME     4
AGE      4
SAL      3
EMAIL    3
LOC      4
dtype: int64

In [49]:
dfNull.dropna()

ID        NAME   AGE      SAL               EMAIL       LOC
2  114.0      Jayesh  27.0  65000.0  jayesh@outlook.com     Thane
4  120.0       Komal  28.0  59700.0     komal@yahoo.com   Sangali
6  140.0      Sachin  29.0  45700.0    sachin@gmail.com  Kolhapur
7  135.0  Vijaykumar  32.0  46940.0     vijay@yahoo.com  Kolhapur

In [50]:
dfNull.dropna(thresh=5)

ID        NAME   AGE      SAL               EMAIL       LOC
0   105.0        Anil  32.0      NaN      anil@gmail.com      Pune
1   106.0      Chetan   NaN  98000.0      chet@yahoo.com     Pawai
2   114.0      Jayesh  27.0  65000.0  jayesh@outlook.com     Thane
4   120.0       Komal  28.0  59700.0     komal@yahoo.com   Sangali
6   140.0      Sachin  29.0  45700.0    sachin@gmail.com  Kolhapur
7   135.0  Vijaykumar  32.0  46940.0     vijay@yahoo.com  Kolhapur
8   498.0       Kiran   NaN  61649.0     kamal@gmail.com     Panji
10  416.0      Bharat   NaN  98746.0    bharat@gmail.com     Latur
12  489.0     Pratham  25.0  46479.0   pratham@gmail.com       NaN

In [51]:
dfNull.dropna(how='all')

ID        NAME   AGE      SAL               EMAIL       LOC
0   105.0        Anil  32.0      NaN      anil@gmail.com      Pune
1   106.0      Chetan   NaN  98000.0      chet@yahoo.com     Pawai
2   114.0      Jayesh  27.0  65000.0  jayesh@outlook.com     Thane
3     NaN      Harish  25.0      NaN    harish@gmail.com       NaN
4   120.0       Komal  28.0  59700.0     komal@yahoo.com   Sangali
5   135.0         NaN   NaN  78700.0                 NaN  Hydrabad
6   140.0      Sachin  29.0  45700.0    sachin@gmail.com  Kolhapur
7   135.0  Vijaykumar  32.0  46940.0     vijay@yahoo.com  Kolhapur
8   498.0       Kiran   NaN  61649.0     kamal@gmail.com     Panji
9     NaN         NaN  25.0  76464.0                 NaN    Barshi
10  416.0      Bharat   NaN  98746.0    bharat@gmail.com     Latur
11    NaN         NaN  40.0      NaN    sachin@gmail.com      Pune
12  489.0     Pratham  25.0  46479.0   pratham@gmail.com       NaN
13  162.0       Shlok  27.0  46497.0                 NaN       NaN
14  648.0         NaN  24.0  45404.0    kanika@gmail.com       NaN

In [52]:
dfNull.dropna(how='any')

ID        NAME   AGE      SAL               EMAIL       LOC
2  114.0      Jayesh  27.0  65000.0  jayesh@outlook.com     Thane
4  120.0       Komal  28.0  59700.0     komal@yahoo.com   Sangali
6  140.0      Sachin  29.0  45700.0    sachin@gmail.com  Kolhapur
7  135.0  Vijaykumar  32.0  46940.0     vijay@yahoo.com  Kolhapur

In [53]:
dfNull.fillna('Dinesh')

ID        NAME     AGE      SAL               EMAIL       LOC
0    105.0        Anil    32.0   Dinesh      anil@gmail.com      Pune
1    106.0      Chetan  Dinesh  98000.0      chet@yahoo.com     Pawai
2    114.0      Jayesh    27.0  65000.0  jayesh@outlook.com     Thane
3   Dinesh      Harish    25.0   Dinesh    harish@gmail.com    Dinesh
4    120.0       Komal    28.0  59700.0     komal@yahoo.com   Sangali
5    135.0      Dinesh  Dinesh  78700.0              Dinesh  Hydrabad
6    140.0      Sachin    29.0  45700.0    sachin@gmail.com  Kolhapur
7    135.0  Vijaykumar    32.0  46940.0     vijay@yahoo.com  Kolhapur
8    498.0       Kiran  Dinesh  61649.0     kamal@gmail.com     Panji
9   Dinesh      Dinesh    25.0  76464.0              Dinesh    Barshi
10   416.0      Bharat  Dinesh  98746.0    bharat@gmail.com     Latur
11  Dinesh      Dinesh    40.0   Dinesh    sachin@gmail.com      Pune
12   489.0     Pratham    25.0  46479.0   pratham@gmail.com    Dinesh
13   162.0       Shlok    27.0  46497.0              Dinesh    Dinesh
14   648.0      Dinesh    24.0  45404.0    kanika@gmail.com    Dinesh

In [54]:
dfNull.fillna(25)

ID        NAME   AGE      SAL               EMAIL       LOC
0   105.0        Anil  32.0     25.0      anil@gmail.com      Pune
1   106.0      Chetan  25.0  98000.0      chet@yahoo.com     Pawai
2   114.0      Jayesh  27.0  65000.0  jayesh@outlook.com     Thane
3    25.0      Harish  25.0     25.0    harish@gmail.com        25
4   120.0       Komal  28.0  59700.0     komal@yahoo.com   Sangali
5   135.0          25  25.0  78700.0                  25  Hydrabad
6   140.0      Sachin  29.0  45700.0    sachin@gmail.com  Kolhapur
7   135.0  Vijaykumar  32.0  46940.0     vijay@yahoo.com  Kolhapur
8   498.0       Kiran  25.0  61649.0     kamal@gmail.com     Panji
9    25.0          25  25.0  76464.0                  25    Barshi
10  416.0      Bharat  25.0  98746.0    bharat@gmail.com     Latur
11   25.0          25  40.0     25.0    sachin@gmail.com      Pune
12  489.0     Pratham  25.0  46479.0   pratham@gmail.com        25
13  162.0       Shlok  27.0  46497.0                  25        25
14  648.0          25  24.0  45404.0    kanika@gmail.com        25

In [55]:
dfNull.fillna(method='ffill')

ID        NAME   AGE      SAL               EMAIL       LOC
0   105.0        Anil  32.0      NaN      anil@gmail.com      Pune
1   106.0      Chetan  32.0  98000.0      chet@yahoo.com     Pawai
2   114.0      Jayesh  27.0  65000.0  jayesh@outlook.com     Thane
3   114.0      Harish  25.0  65000.0    harish@gmail.com     Thane
4   120.0       Komal  28.0  59700.0     komal@yahoo.com   Sangali
5   135.0       Komal  28.0  78700.0     komal@yahoo.com  Hydrabad
6   140.0      Sachin  29.0  45700.0    sachin@gmail.com  Kolhapur
7   135.0  Vijaykumar  32.0  46940.0     vijay@yahoo.com  Kolhapur
8   498.0       Kiran  32.0  61649.0     kamal@gmail.com     Panji
9   498.0       Kiran  25.0  76464.0     kamal@gmail.com    Barshi
10  416.0      Bharat  25.0  98746.0    bharat@gmail.com     Latur
11  416.0      Bharat  40.0  98746.0    sachin@gmail.com      Pune
12  489.0     Pratham  25.0  46479.0   pratham@gmail.com      Pune
13  162.0       Shlok  27.0  46497.0   pratham@gmail.com      Pune
14  648.0       Shlok  24.0  45404.0    kanika@gmail.com      Pune

In [56]:
dfNull.fillna(method='bfill')

ID        NAME   AGE      SAL               EMAIL       LOC
0   105.0        Anil  32.0  98000.0      anil@gmail.com      Pune
1   106.0      Chetan  27.0  98000.0      chet@yahoo.com     Pawai
2   114.0      Jayesh  27.0  65000.0  jayesh@outlook.com     Thane
3   120.0      Harish  25.0  59700.0    harish@gmail.com   Sangali
4   120.0       Komal  28.0  59700.0     komal@yahoo.com   Sangali
5   135.0      Sachin  29.0  78700.0    sachin@gmail.com  Hydrabad
6   140.0      Sachin  29.0  45700.0    sachin@gmail.com  Kolhapur
7   135.0  Vijaykumar  32.0  46940.0     vijay@yahoo.com  Kolhapur
8   498.0       Kiran  25.0  61649.0     kamal@gmail.com     Panji
9   416.0      Bharat  25.0  76464.0    bharat@gmail.com    Barshi
10  416.0      Bharat  40.0  98746.0    bharat@gmail.com     Latur
11  489.0     Pratham  40.0  46479.0    sachin@gmail.com      Pune
12  489.0     Pratham  25.0  46479.0   pratham@gmail.com       NaN
13  162.0       Shlok  27.0  46497.0    kanika@gmail.com       NaN
14  648.0         NaN  24.0  45404.0    kanika@gmail.com       NaN

### Concatining

- Concat
- Merge

In [57]:
dfc1 = pd.DataFrame({'EMP_ID':[101,102,103,104,105],
                     'EMP_NAME' :['Isha','Priya','Neha','Rahul','Abhishek'],
                     'EMP_DEPT' :['E-101','E-104','E-101','E-102','E-101'],
                     'CONTACT_NO':[1234567890,1234567890,1234567890,1234567890,1234567890],
                     'EMAIL_ID' :['isha@gmail.com','priya@yahoo.com','neha@gmail.com','rahul@yahoo.com','abhishek@gmail.com'],
                     'EMP_HEAD_ID' :[105,103,101,105,102]})

In [58]:
dfc1

EMP_ID  EMP_NAME EMP_DEPT  CONTACT_NO            EMAIL_ID  EMP_HEAD_ID
0     101      Isha    E-101  1234567890      isha@gmail.com          105
1     102     Priya    E-104  1234567890     priya@yahoo.com          103
2     103      Neha    E-101  1234567890      neha@gmail.com          101
3     104     Rahul    E-102  1234567890     rahul@yahoo.com          105
4     105  Abhishek    E-101  1234567890  abhishek@gmail.com          102

In [59]:
dfc2 = pd.DataFrame({'EMP_DEPT' :['E-101','E-102','E-103','E-104','E-105'],
                     'DEPT_NAME':['HR','Development','Hous Keeping','Sales','Purchage'],
                     'DEPT_OFF':['Monday','Tuesday','Saturday','Sunday','Tuesday',],
                     'EMP_ID':[105,101,103,102,104]
                    })

In [60]:
dfc2

EMP_DEPT     DEPT_NAME  DEPT_OFF  EMP_ID
0    E-101            HR    Monday     105
1    E-102   Development   Tuesday     101
2    E-103  Hous Keeping  Saturday     103
3    E-104         Sales    Sunday     102
4    E-105      Purchage   Tuesday     104

In [61]:
pd.concat([dfc1,dfc2],ignore_index=True)

EMP_ID  EMP_NAME EMP_DEPT    CONTACT_NO            EMAIL_ID  EMP_HEAD_ID  \
0     101      Isha    E-101  1.234568e+09      isha@gmail.com        105.0   
1     102     Priya    E-104  1.234568e+09     priya@yahoo.com        103.0   
2     103      Neha    E-101  1.234568e+09      neha@gmail.com        101.0   
3     104     Rahul    E-102  1.234568e+09     rahul@yahoo.com        105.0   
4     105  Abhishek    E-101  1.234568e+09  abhishek@gmail.com        102.0   
5     105       NaN    E-101           NaN                 NaN          NaN   
6     101       NaN    E-102           NaN                 NaN          NaN   
7     103       NaN    E-103           NaN                 NaN          NaN   
8     102       NaN    E-104           NaN                 NaN          NaN   
9     104       NaN    E-105           NaN                 NaN          NaN   

      DEPT_NAME  DEPT_OFF  
0           NaN       NaN  
1           NaN       NaN  
2           NaN       NaN  
3           NaN       NaN  
4           NaN       NaN  
5            HR    Monday  
6   Development   Tuesday  
7  Hous Keeping  Saturday  
8         Sales    Sunday  
9      Purchage   Tuesday

In [62]:
pd.concat([dfc1,dfc2],axis=1)

EMP_ID  EMP_NAME EMP_DEPT  CONTACT_NO            EMAIL_ID  EMP_HEAD_ID  \
0     101      Isha    E-101  1234567890      isha@gmail.com          105   
1     102     Priya    E-104  1234567890     priya@yahoo.com          103   
2     103      Neha    E-101  1234567890      neha@gmail.com          101   
3     104     Rahul    E-102  1234567890     rahul@yahoo.com          105   
4     105  Abhishek    E-101  1234567890  abhishek@gmail.com          102   

  EMP_DEPT     DEPT_NAME  DEPT_OFF  EMP_ID  
0    E-101            HR    Monday     105  
1    E-102   Development   Tuesday     101  
2    E-103  Hous Keeping  Saturday     103  
3    E-104         Sales    Sunday     102  
4    E-105      Purchage   Tuesday     104

In [63]:
pd.concat([dfc1,dfc2],keys=['Employee','Department'])

EMP_ID  EMP_NAME EMP_DEPT    CONTACT_NO            EMAIL_ID  \
Employee   0     101      Isha    E-101  1.234568e+09      isha@gmail.com   
           1     102     Priya    E-104  1.234568e+09     priya@yahoo.com   
           2     103      Neha    E-101  1.234568e+09      neha@gmail.com   
           3     104     Rahul    E-102  1.234568e+09     rahul@yahoo.com   
           4     105  Abhishek    E-101  1.234568e+09  abhishek@gmail.com   
Department 0     105       NaN    E-101           NaN                 NaN   
           1     101       NaN    E-102           NaN                 NaN   
           2     103       NaN    E-103           NaN                 NaN   
           3     102       NaN    E-104           NaN                 NaN   
           4     104       NaN    E-105           NaN                 NaN   

              EMP_HEAD_ID     DEPT_NAME  DEPT_OFF  
Employee   0        105.0           NaN       NaN  
           1        103.0           NaN       NaN  
           2        101.0           NaN       NaN  
           3        105.0           NaN       NaN  
           4        102.0           NaN       NaN  
Department 0          NaN            HR    Monday  
           1          NaN   Development   Tuesday  
           2          NaN  Hous Keeping  Saturday  
           3          NaN         Sales    Sunday  
           4          NaN      Purchage   Tuesday

In [64]:
dfc1['Sal'] = 16846,16160,11513,46464,79465

In [65]:
dfc1

EMP_ID  EMP_NAME EMP_DEPT  CONTACT_NO            EMAIL_ID  EMP_HEAD_ID  \
0     101      Isha    E-101  1234567890      isha@gmail.com          105   
1     102     Priya    E-104  1234567890     priya@yahoo.com          103   
2     103      Neha    E-101  1234567890      neha@gmail.com          101   
3     104     Rahul    E-102  1234567890     rahul@yahoo.com          105   
4     105  Abhishek    E-101  1234567890  abhishek@gmail.com          102   

     Sal  
0  16846  
1  16160  
2  11513  
3  46464  
4  79465

### Merge

In [66]:
pd.merge(dfc1,dfc2,on='EMP_ID',how='left')

EMP_ID  EMP_NAME EMP_DEPT_x  CONTACT_NO            EMAIL_ID  EMP_HEAD_ID  \
0     101      Isha      E-101  1234567890      isha@gmail.com          105   
1     102     Priya      E-104  1234567890     priya@yahoo.com          103   
2     103      Neha      E-101  1234567890      neha@gmail.com          101   
3     104     Rahul      E-102  1234567890     rahul@yahoo.com          105   
4     105  Abhishek      E-101  1234567890  abhishek@gmail.com          102   

     Sal EMP_DEPT_y     DEPT_NAME  DEPT_OFF  
0  16846      E-102   Development   Tuesday  
1  16160      E-104         Sales    Sunday  
2  11513      E-103  Hous Keeping  Saturday  
3  46464      E-105      Purchage   Tuesday  
4  79465      E-101            HR    Monday

### Filter

In [67]:
df

Customer_id  Gender  Age         Category  Quantity    Price  \
0         C241288  Female   28         Clothing         5  1500.40   
1         C111565    Male   21            Shoes         3  1800.51   
2         C266599    Male   20         Clothing         1   300.08   
3         C988172  Female   66            Shoes         5  3000.85   
4         C189076  Female   53            Books         4    60.60   
...           ...     ...  ...              ...       ...      ...   
99452     C441542  Female   45         Souvenir         5    58.65   
99453     C569580    Male   27  Food & Beverage         2    10.46   
99454     C103292    Male   63  Food & Beverage         2    10.46   
99455     C800631    Male   56       Technology         4  4200.00   
99456     C273973  Female   36         Souvenir         3    35.19   

      Payment_method     Shopping_mall  
0        Credit Card            Kanyon  
1         Debit Card    Forum Istanbul  
2               Cash         Metrocity  
3        Credit Card      Metropol AVM  
4               Cash            Kanyon  
...              ...               ...  
99452    Credit Card            Kanyon  
99453           Cash    Forum Istanbul  
99454     Debit Card         Metrocity  
99455           Cash      Istinye Park  
99456    Credit Card  Mall of Istanbul  

[99457 rows x 8 columns]

In [68]:
df[(df['Gender']=='Female') & (df['Age']>18)]

Customer_id  Gender  Age   Category  Quantity    Price Payment_method  \
0         C241288  Female   28   Clothing         5  1500.40    Credit Card   
3         C988172  Female   66      Shoes         5  3000.85    Credit Card   
4         C189076  Female   53      Books         4    60.60           Cash   
5         C657758  Female   28   Clothing         5  1500.40    Credit Card   
6         C151197  Female   49  Cosmetics         1    40.66           Cash   
...           ...     ...  ...        ...       ...      ...            ...   
99447     C288090  Female   37       Toys         3   107.52           Cash   
99448     C231387  Female   65      Shoes         4  2400.68    Credit Card   
99450     C226974  Female   28      Books         1    15.15           Cash   
99452     C441542  Female   45   Souvenir         5    58.65    Credit Card   
99456     C273973  Female   36   Souvenir         3    35.19    Credit Card   

          Shopping_mall  
0                Kanyon  
3          Metropol AVM  
4                Kanyon  
5        Forum Istanbul  
6          Istinye Park  
...                 ...  
99447      Metropol AVM  
99448      Metropol AVM  
99450      Zorlu Center  
99452            Kanyon  
99456  Mall of Istanbul  

[58403 rows x 8 columns]

In [69]:
df[(df['Age']>50)&(df['Price']>3000)].max()

Customer_id            C998781
Gender                    Male
Age                         69
Category            Technology
Quantity                     5
Price                   5250.0
Payment_method      Debit Card
Shopping_mall     Zorlu Center
dtype: object

In [70]:
df[(df['Age']>50)&(df['Price']>3000)]

Customer_id  Gender  Age    Category  Quantity    Price Payment_method  \
3         C988172  Female   66       Shoes         5  3000.85    Credit Card   
73        C136117  Female   57       Shoes         5  3000.85     Debit Card   
146       C178734    Male   52       Shoes         5  3000.85           Cash   
177       C270129  Female   66  Technology         3  3150.00     Debit Card   
215       C256730    Male   53       Shoes         5  3000.85           Cash   
...           ...     ...  ...         ...       ...      ...            ...   
99173     C540953  Female   55  Technology         4  4200.00           Cash   
99184     C147495  Female   63       Shoes         5  3000.85    Credit Card   
99307     C200968  Female   54       Shoes         5  3000.85           Cash   
99332     C232954  Female   53       Shoes         5  3000.85    Credit Card   
99455     C800631    Male   56  Technology         4  4200.00           Cash   

           Shopping_mall  
3           Metropol AVM  
73     Emaar Square Mall  
146               Kanyon  
177          Cevahir AVM  
215         Zorlu Center  
...                  ...  
99173        Cevahir AVM  
99184             Kanyon  
99307   Mall of Istanbul  
99332          Metrocity  
99455       Istinye Park  

[1796 rows x 8 columns]

In [71]:
df['Shopping_mall'].value_counts()

Mall of Istanbul     19943
Kanyon               19823
Metrocity            15011
Metropol AVM         10161
Istinye Park          9781
Zorlu Center          5075
Cevahir AVM           4991
Forum Istanbul        4947
Viaport Outlet        4914
Emaar Square Mall     4811
Name: Shopping_mall, dtype: int64

In [72]:
df[(df['Shopping_mall']=='Metropol AVM')&(df['Payment_method']=='Credit Card')&(df['Gender']=='Female')&(df['Age']>60)&(df['Price']>3000)]

Customer_id  Gender  Age    Category  Quantity    Price Payment_method  \
3         C988172  Female   66       Shoes         5  3000.85    Credit Card   
2751      C156390  Female   61  Technology         3  3150.00    Credit Card   
15793     C156790  Female   61       Shoes         5  3000.85    Credit Card   
24446     C896185  Female   63  Technology         5  5250.00    Credit Card   
27522     C144061  Female   67       Shoes         5  3000.85    Credit Card   
30554     C272262  Female   68       Shoes         5  3000.85    Credit Card   
41985     C157996  Female   67  Technology         5  5250.00    Credit Card   
42493     C263123  Female   67  Technology         3  3150.00    Credit Card   
54222     C227883  Female   61  Technology         5  5250.00    Credit Card   
59725     C182586  Female   68       Shoes         5  3000.85    Credit Card   
66744     C242867  Female   68       Shoes         5  3000.85    Credit Card   
72442     C380769  Female   67  Technology         5  5250.00    Credit Card   
76287     C120968  Female   65       Shoes         5  3000.85    Credit Card   
78002     C277053  Female   65  Technology         3  3150.00    Credit Card   
86343     C166407  Female   62  Technology         4  4200.00    Credit Card   

      Shopping_mall  
3      Metropol AVM  
2751   Metropol AVM  
15793  Metropol AVM  
24446  Metropol AVM  
27522  Metropol AVM  
30554  Metropol AVM  
41985  Metropol AVM  
42493  Metropol AVM  
54222  Metropol AVM  
59725  Metropol AVM  
66744  Metropol AVM  
72442  Metropol AVM  
76287  Metropol AVM  
78002  Metropol AVM  
86343  Metropol AVM

In [73]:
df['Category'].unique()

array(['Clothing', 'Shoes', 'Books', 'Cosmetics', 'Food & Beverage',
       'Toys', 'Technology', 'Souvenir'], dtype=object)

In [74]:
df[(df['Category']=='Shoes')&(df['Price']>2000)&(df['Quantity']==5)&(df['Gender']=='Female')
     &(df['Shopping_mall']=='Kanyon')&(df['Age']>50)&(df['Payment_method']=='Credit Card')]

Customer_id  Gender  Age Category  Quantity    Price Payment_method  \
750       C182606  Female   52    Shoes         5  3000.85    Credit Card   
10278     C239733  Female   55    Shoes         5  3000.85    Credit Card   
11070     C229363  Female   52    Shoes         5  3000.85    Credit Card   
11650     C206174  Female   59    Shoes         5  3000.85    Credit Card   
20489     C475496  Female   62    Shoes         5  3000.85    Credit Card   
22738     C669846  Female   64    Shoes         5  3000.85    Credit Card   
28377     C310851  Female   51    Shoes         5  3000.85    Credit Card   
36065     C294725  Female   55    Shoes         5  3000.85    Credit Card   
39116     C230301  Female   52    Shoes         5  3000.85    Credit Card   
40523     C254174  Female   64    Shoes         5  3000.85    Credit Card   
41816     C274860  Female   59    Shoes         5  3000.85    Credit Card   
42298     C862756  Female   67    Shoes         5  3000.85    Credit Card   
47705     C257298  Female   64    Shoes         5  3000.85    Credit Card   
48871     C214128  Female   53    Shoes         5  3000.85    Credit Card   
49006     C109999  Female   57    Shoes         5  3000.85    Credit Card   
60083     C460905  Female   67    Shoes         5  3000.85    Credit Card   
63879     C106241  Female   53    Shoes         5  3000.85    Credit Card   
64249     C353357  Female   60    Shoes         5  3000.85    Credit Card   
67834     C842430  Female   57    Shoes         5  3000.85    Credit Card   
88476     C247525  Female   57    Shoes         5  3000.85    Credit Card   
93633     C125850  Female   52    Shoes         5  3000.85    Credit Card   
94238     C323332  Female   64    Shoes         5  3000.85    Credit Card   
99184     C147495  Female   63    Shoes         5  3000.85    Credit Card   

      Shopping_mall  
750          Kanyon  
10278        Kanyon  
11070        Kanyon  
11650        Kanyon  
20489        Kanyon  
22738        Kanyon  
28377        Kanyon  
36065        Kanyon  
39116        Kanyon  
40523        Kanyon  
41816        Kanyon  
42298        Kanyon  
47705        Kanyon  
48871        Kanyon  
49006        Kanyon  
60083        Kanyon  
63879        Kanyon  
64249        Kanyon  
67834        Kanyon  
88476        Kanyon  
93633        Kanyon  
94238        Kanyon  
99184        Kanyon

# Numpy

- Numerical Python is python library used for work wih arrays.
- Used for Numerical Cal and Complex Cal

In [75]:
import numpy as np

In [76]:
np.__version__

'1.23.5'

In [77]:
a = np.array([91,64,69,66,56,64,46,26])

In [78]:
type(a)

numpy.ndarray

In [79]:
a

array([91, 64, 69, 66, 56, 64, 46, 26])

In [82]:
b = np.array([94,99,61,65,16,51,64,89,49,24],dtype='complex')

In [83]:
b

array([94.+0.j, 99.+0.j, 61.+0.j, 65.+0.j, 16.+0.j, 51.+0.j, 64.+0.j,
       89.+0.j, 49.+0.j, 24.+0.j])

In [84]:
c = np.array([94,99,61,65,16,51,64,89,49,24],dtype='int64')

In [85]:
c

array([94, 99, 61, 65, 16, 51, 64, 89, 49, 24], dtype=int64)

In [86]:
a.mean()

60.25

In [87]:
a/2

array([45.5, 32. , 34.5, 33. , 28. , 32. , 23. , 13. ])

In [89]:
Li = [94,99,61,65,16,51,64,89,49,24]

In [90]:
type(Li)

list

In [91]:
Ni = np.array([94,99,61,65,16,51,64,89,49,24])

In [92]:
type(Ni)

numpy.ndarray

In [88]:
import sys

In [97]:
sys.getsizeof(16)*len(Li)

280

In [98]:
sys.getsizeof(16)*len(Ni)

280

In [100]:
#1D
Ni.ndim

1

In [109]:
Ne = np.array([[64,46,61,'Java'],[98,94,84,89]])

In [110]:
Ne

array([['64', '46', '61', 'Java'],
       ['98', '94', '84', '89']], dtype='<U11')

In [111]:
Ne.ndim

2

In [112]:
N3D = np.array([[[36,96,76,46],[79,56,68,60],[89,98,65,59]]])

In [113]:
N3D

array([[[36, 96, 76, 46],
        [79, 56, 68, 60],
        [89, 98, 65, 59]]])

In [115]:
N3D.ndim

3

In [120]:
Ne

array([['64', '46', '61', 'Java'],
       ['98', '94', '84', '89']], dtype='<U11')

In [118]:
Ne.shape

(2, 4)

In [121]:
Ne[0][3]

'Java'

In [123]:
Ne[1][3]

'89'

In [124]:
N3D

array([[[36, 96, 76, 46],
        [79, 56, 68, 60],
        [89, 98, 65, 59]]])

In [131]:
N3D[0][1]

array([79, 56, 68, 60])

In [144]:
Nb = np.array([[[794,494,494,646],[49,441,61,64]],
              [[494,464,94,984],[44,46,46,56]]])

In [145]:
Nb.ndim

3

In [152]:
Nb[0][1][1]

441

In [155]:
Nb[1][0][2]

94

In [159]:
Ne

array([['64', '46', '61', 'Java'],
       ['98', '94', '84', '89']], dtype='<U11')

In [160]:
Ne.shape

(2, 4)

In [161]:
Ne.reshape(4,2)

array([['64', '46'],
       ['61', 'Java'],
       ['98', '94'],
       ['84', '89']], dtype='<U11')

In [162]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [165]:
np.zeros([20,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [166]:
np.ones(85)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [167]:
np.ones([4,20])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [178]:
a1 = a

In [179]:
a1

array([91, 64, 69, 66, 56, 64, 46, 26])

In [180]:
a2 = [44,66,16,97,54,18,16,16]

In [181]:
np.multiply(a1,a2)

array([4004, 4224, 1104, 6402, 3024, 1152,  736,  416])

In [182]:
#Generate No.
np.arange(5,25,5)

array([ 5, 10, 15, 20])

In [183]:
np.dot(a1,a2)

21062

In [185]:
#Indentity
np.eye(45,59,dtype='int64')

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [187]:
np.eye(3,5,dtype='complex')

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]])

In [189]:
#to generate random no.
np.random.randint(15)

11

In [191]:
# 0-1
np.random.rand(10)

array([0.45114063, 0.7924881 , 0.15862154, 0.46693116, 0.66937371,
       0.74208879, 0.45240685, 0.15453678, 0.71852565, 0.55953161])

In [194]:
np.random.randint(10,35,size=[9,3])

array([[13, 31, 28],
       [20, 33, 30],
       [22, 16, 27],
       [24, 25, 32],
       [29, 12, 12],
       [28, 14, 20],
       [17, 15, 34],
       [16, 23, 17],
       [13, 15, 16]])

In [196]:
np.full((4,4),[45])

array([[45, 45, 45, 45],
       [45, 45, 45, 45],
       [45, 45, 45, 45],
       [45, 45, 45, 45]])